/* URBAN SOCIETY - CUSTOMERS */
(function(){
  if(window.__urbanCustomersInstalled)return;window.__urbanCustomersInstalled=true;
  const OWNER='mendozaosornio010305@gmail.com';const $=id=>document.getElementById(id);const money=v=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(v||0));const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');let customers=[],orders=[];
  function toast(msg){const e=$('suite-toast');e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
  function aggregate(){return customers.map(c=>{const mine=orders.filter(o=>o.user_id===c.user_id),valid=mine.filter(o=>o.status!=='Cancelado'),spent=valid.reduce((s,o)=>s+Number(o.total||0),0),latest=mine.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0]||null,active=mine.some(o=>!['Entregado','Cancelado'].includes(o.status));return{...c,mine,valid,spent,latest,active};});}
  function render(){const q=String($('customers-search').value||'').trim().toLowerCase(),filter=$('customers-filter').value;const rows=aggregate().filter(c=>{const text=`${c.name||''} ${c.email||''} ${c.phone||''}`.toLowerCase();if(q&&!text.includes(q))return false;if(filter==='buyers'&&!c.valid.length)return false;if(filter==='active'&&!c.active)return false;return true;});$('customers-list').innerHTML=rows.length?rows.map(c=>`<tr><td><strong>${esc(c.name||c.email.split('@')[0]||'Cliente')}</strong><div class="suite-muted">${esc(c.email)}</div>${c.phone?`<div class="suite-muted">${esc(c.phone)}</div>`:''}</td><td>${c.mine.length}</td><td><strong>${money(c.spent)}</strong></td><td>${c.latest?esc(new Intl.DateTimeFormat('es-MX',{dateStyle:'medium'}).format(new Date(c.latest.created_at))):'—'}</td><td>${c.active?'<span class="suite-chip warn">Pedido activo</span>':c.valid.length?'<span class="suite-chip good">Cliente</span>':'<span class="suite-chip">Sin compras</span>'}</td><td><button class="suite-btn" type="button" onclick="openCustomer('${esc(c.user_id)}')">Ver</button></td></tr>`).join(''):'<tr><td colspan="6">No hay clientes con ese filtro.</td></tr>';}
  async function load(){const [cR,oR,sR]=await Promise.all([window.urbanSupabase.from('customer_profiles').select('*').order('created_at',{ascending:false}),window.urbanSupabase.from('orders').select('id,user_id,created_at,total,status,payment_method,products').not('user_id','is',null).order('created_at',{ascending:false}),window.urbanSupabase.from('staff_members').select('user_id')]);if(cR.error)throw cR.error;if(oR.error)throw oR.error;const staffIds=new Set((sR.data||[]).map(s=>s.user_id));customers=(cR.data||[]).filter(c=>String(c.email||'').toLowerCase()!==OWNER&&!staffIds.has(c.user_id));orders=oR.data||[];const agg=aggregate();$('customers-count').textContent=customers.length;$('customers-buyers').textContent=agg.filter(c=>c.valid.length).length;$('customers-sales').textContent=money(agg.reduce((s,c)=>s+c.spent,0));render();}
  function orderRows(c){if(!c.mine.length)return '<div class="suite-empty">Sin pedidos.</div>';return `<div class="suite-list">${c.mine.slice(0,10).map(o=>`<div class="suite-row"><div><strong>Pedido #${esc(o.id.slice(0,8))}…</strong><small>${esc(new Intl.DateTimeFormat('es-MX',{dateStyle:'medium'}).format(new Date(o.created_at)))} · ${esc(o.status)}</small></div><strong>${money(o.total)}</strong></div>`).join('')}</div>`}
  function openCustomer(id){const c=aggregate().find(x=>x.user_id===id);if(!c)return;$('customer-modal-title').textContent=c.name||c.email;$('customer-modal-content').innerHTML=`<div class="suite-grid cols-3"><div class="suite-card suite-metric"><span>Pedidos</span><strong>${c.mine.length}</strong></div><div class="suite-card suite-metric"><span>Total</span><strong>${money(c.spent)}</strong></div><div class="suite-card suite-metric"><span>Activos</span><strong>${c.mine.filter(o=>!['Entregado','Cancelado'].includes(o.status)).length}</strong></div></div><div class="suite-divider"></div><div class="suite-row"><div><strong>${esc(c.email)}</strong><small>${esc(c.phone||'Sin teléfono')}</small></div></div><div class="suite-divider"></div><h3>Notas internas</h3><form id="customer-notes-form" class="suite-form"><textarea id="customer-notes" maxlength="1000" placeholder="Preferencias, seguimiento, observaciones...">${esc(c.notes||'')}</textarea><button class="suite-btn primary" type="submit">GUARDAR NOTAS</button></form><div class="suite-divider"></div><h3>Pedidos recientes</h3>${orderRows(c)}`;$('customer-notes-form').addEventListener('submit',e=>saveNotes(e,c));$('customer-modal').classList.add('active');}
  async function saveNotes(e,c){e.preventDefault();const notes=$('customer-notes').value.trim();const{error}=await window.urbanSupabase.from('customer_profiles').update({notes,updated_at:new Date().toISOString()}).eq('user_id',c.user_id);if(error)return alert(error.message);c.notes=notes;toast('Notas guardadas.');}
  function close(){ $('customer-modal').classList.remove('active'); }
  document.addEventListener('DOMContentLoaded',async()=>{if(await window.verificarAcceso?.('customers')===false)return;$('customers-search').addEventListener('input',render);$('customers-filter').addEventListener('change',render);$('customers-refresh').addEventListener('click',()=>load().catch(console.error));document.querySelector('[data-close-customer]').addEventListener('click',close);$('customer-modal').addEventListener('click',e=>{if(e.target===$('customer-modal'))close();});try{await load();}catch(e){console.error(e);$('customers-list').innerHTML='<tr><td colspan="6">No se pudo cargar clientes.</td></tr>';}});window.openCustomer=openCustomer;
})();
