/* URBAN SOCIETY - REPORTS */
(function(){
  if(window.__urbanReportsInstalled)return;window.__urbanReportsInstalled=true;
  const $=id=>document.getElementById(id);const money=v=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(v||0));
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
  function localDateInput(d){const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
  function setRange(days){const end=new Date();const start=new Date();if(days!=='today')start.setDate(start.getDate()-Number(days)+1);$('report-from').value=localDateInput(start);$('report-to').value=localDateInput(end);load();}
  function bounds(){const from=$('report-from').value,to=$('report-to').value;if(!from||!to)return null;return{start:new Date(`${from}T00:00:00`).toISOString(),end:new Date(`${to}T23:59:59.999`).toISOString(),from,to};}
  function metric(label,value,detail,cls=''){return `<article class="suite-card suite-metric ${cls}"><span>${esc(label)}</span><strong>${esc(value)}</strong><small class="suite-muted">${esc(detail)}</small></article>`}
  const dayKey=value=>localDateInput(new Date(value));
  function renderDaily(pos,orders,range){const map=new Map();let cursor=new Date(`${range.from}T00:00:00`),end=new Date(`${range.to}T00:00:00`);while(cursor<=end){map.set(localDateInput(cursor),0);cursor.setDate(cursor.getDate()+1);}pos.forEach(s=>map.set(dayKey(s.created_at),(map.get(dayKey(s.created_at))||0)+Number(s.total||0)-Number(s.returned_total||0)));orders.filter(o=>o.status!=='Cancelado').forEach(o=>map.set(dayKey(o.created_at),(map.get(dayKey(o.created_at))||0)+Number(o.total||0)));const values=[...map.entries()],max=Math.max(1,...values.map(([,v])=>v));$('report-daily').innerHTML=values.map(([day,v])=>`<div class="suite-spark-bar" style="height:${Math.max(3,Math.round(v/max*100))}%" data-label="${esc(day)} · ${esc(money(v))}" title="${esc(day)} ${esc(money(v))}"></div>`).join('');}
  function renderPayments(pos){const groups={Efectivo:0,Tarjeta:0,Transferencia:0};pos.forEach(s=>groups[s.payment_method]=(groups[s.payment_method]||0)+Number(s.total||0));const max=Math.max(1,...Object.values(groups));$('report-payments').innerHTML=Object.entries(groups).map(([k,v])=>`<div class="suite-chart-row"><span class="suite-chart-label">${esc(k)}</span><div class="suite-bar"><span style="width:${Math.round(v/max*100)}%"></span></div><span class="suite-chart-value">${esc(money(v))}</span></div>`).join('');}
  function renderProducts(pos,orders){const map=new Map();function add(items,channel){(Array.isArray(items)?items:[]).forEach(i=>{const key=`${i.productId||i.name}::${i.size||''}`,row=map.get(key)||{name:i.name||'Producto',size:i.size||'',qty:0,amount:0,channels:new Set()};row.qty+=Number(i.quantity||0);row.amount+=Number(i.total??i.subtotal??Number(i.price||0)*Number(i.quantity||0));row.channels.add(channel);map.set(key,row);});}pos.forEach(s=>add(s.items,'Tienda'));orders.filter(o=>o.status!=='Cancelado').forEach(o=>add(o.products,'Online'));const rows=[...map.values()].sort((a,b)=>b.qty-a.qty).slice(0,30);$('report-products').innerHTML=rows.length?rows.map(r=>`<tr><td><strong>${esc(r.name)}</strong>${r.size?`<div class="suite-muted">Talla ${esc(r.size)}</div>`:''}</td><td>${r.qty}</td><td>${money(r.amount)}</td><td>${[...r.channels].map(c=>`<span class="suite-chip">${esc(c)}</span>`).join(' ')}</td></tr>`).join(''):'<tr><td colspan="4">Sin ventas en este periodo.</td></tr>';}
  async function load(){if(await window.verificarAcceso?.('reports')===false)return;const range=bounds();if(!range)return;const btn=$('report-refresh');btn.disabled=true;btn.textContent='CARGANDO...';try{const[posR,ordersR,retR]=await Promise.all([window.urbanSupabase.from('pos_sales').select('id,created_at,payment_method,items,subtotal,discount_amount,total,returned_total').gte('created_at',range.start).lte('created_at',range.end),window.urbanSupabase.from('orders').select('id,created_at,status,products,total').gte('created_at',range.start).lte('created_at',range.end),window.urbanSupabase.from('pos_returns').select('id,created_at,refund_amount').gte('created_at',range.start).lte('created_at',range.end)]);const error=posR.error||ordersR.error||retR.error;if(error)throw error;const pos=posR.data||[],orders=ordersR.data||[],returns=retR.data||[],posSales=pos.reduce((s,x)=>s+Number(x.total||0),0),online=orders.filter(x=>x.status!=='Cancelado').reduce((s,x)=>s+Number(x.total||0),0),refunds=returns.reduce((s,x)=>s+Number(x.refund_amount||0),0),net=posSales+online-refunds,count=pos.length+orders.filter(x=>x.status!=='Cancelado').length,avg=count?net/count:0,discounts=pos.reduce((s,x)=>s+Number(x.discount_amount||0),0);$('report-metrics').innerHTML=[metric('Ventas netas',money(net),`${count} operaciones`,'suite-positive'),metric('Tienda física',money(posSales-refunds),`${pos.length} ventas · neto de devoluciones`),metric('Tienda online',money(online),`${orders.filter(x=>x.status!=='Cancelado').length} pedidos`),metric('Ticket promedio',money(avg),`Descuentos POS ${money(discounts)}`),metric('Devoluciones',money(refunds),`${returns.length} movimientos`,refunds?'suite-negative':''),metric('Venta bruta',money(posSales+online),'Antes de devoluciones'),metric('Piezas POS',String(pos.reduce((s,x)=>s+(x.items||[]).reduce((a,i)=>a+Number(i.quantity||0),0),0)),'Piezas vendidas en mostrador'),metric('Pedidos cancelados',String(orders.filter(x=>x.status==='Cancelado').length),'No cuentan en ventas')].join('');renderDaily(pos,orders,range);renderPayments(pos);renderProducts(pos,orders);}catch(e){console.error(e);$('report-metrics').innerHTML=`<div class="suite-card suite-empty">No se pudo cargar el reporte: ${esc(e.message||'Error')}</div>`;}finally{btn.disabled=false;btn.textContent='ACTUALIZAR';}}
  document.addEventListener('DOMContentLoaded',()=>{const today=new Date();$('report-to').value=localDateInput(today);const start=new Date();start.setDate(start.getDate()-6);$('report-from').value=localDateInput(start);document.querySelectorAll('[data-report-range]').forEach(b=>b.addEventListener('click',()=>setRange(b.dataset.reportRange)));$('report-refresh').addEventListener('click',load);load();});
})();
