/* URBAN SOCIETY - STAFF LOGIN */
(function(){
  if(window.__urbanStaffLoginInstalled)return;window.__urbanStaffLoginInstalled=true;
  const OWNER='mendozaosornio010305@gmail.com';const $=id=>document.getElementById(id);
  function status(msg,bad=false){const e=$('staff-login-status');e.textContent=msg;e.style.color=bad?'#ff8f9b':'#8fdbaa';}
  async function routeUser(user){const email=String(user?.email||'').toLowerCase();if(email===OWNER){location.replace('admin.html');return;}const{data,error}=await window.urbanSupabase.from('staff_members').select('active,permissions').eq('user_id',user.id).maybeSingle();if(error||!data||data.active===false){await window.urbanSupabase.auth.signOut();throw new Error('Esta cuenta no tiene acceso activo al sistema.');}const p=data.permissions||{};const order=[['dashboard','admin.html'],['pos','pos.html'],['cash','cash.html'],['products','products.html'],['orders','orders.html'],['returns','returns.html'],['inventory','inventory.html'],['reports','reports.html'],['customers','customers.html'],['settings','settings.html']];const target=order.find(([k])=>p.all||p[k]);if(!target){await window.urbanSupabase.auth.signOut();throw new Error('Tu cuenta no tiene módulos habilitados.');}const params=new URLSearchParams(location.search);const requested=params.get('return');location.replace(requested&&requested.endsWith('.html')?requested:target[1]);}
  async function submit(e){e.preventDefault();const button=$('staff-login-submit');button.disabled=true;button.textContent='ENTRANDO...';status('Validando acceso...');try{const{data,error}=await window.urbanSupabase.auth.signInWithPassword({email:$('staff-login-email').value.trim(),password:$('staff-login-password').value});if(error)throw error;await routeUser(data.user);}catch(err){status(err.message||'No se pudo iniciar sesión.',true);button.disabled=false;button.textContent='ENTRAR AL SISTEMA';}}
  document.addEventListener('DOMContentLoaded',async()=>{$('staff-login-form').addEventListener('submit',submit);const{data}=await window.urbanSupabase.auth.getUser();if(data?.user){try{await routeUser(data.user);}catch(_){} }});
})();
